### ISSUE TITLE
Error en visual

### ISSUE THREAD

**Issue by JessicaSuarezAvila** [DrLAlbertoAngelesH/SistemasDeManufactura-2024#274]
Hola profe Buenas Noches, ya no me sale mi rama en visual, abrí mi carpeta del escritorio y no me apareció, incluso puse git branch y no me aparece, ya no abrí visual desde mi toma de tiempos en clase.
![image](https://github.com/user-attachments/assets/097424bc-f562-4069-ae08-7468bbb6d04b)

**Comment by DrLAlbertoAngelesH** [comment]
Es como si hubieras borrado el archivo .git 🤷 que debe de estar en tu
carpeta ITQ

**Comment by JessicaSuarezAvila** [comment]
![Imagen de WhatsApp 2024-10-11 a las 00 21 52_1ceda63a](https://github.com/user-attachments/assets/6478bf72-d605-473a-a111-34cc2256e490)
El día que pase a hacer mi prueba al terminar usted me pidió que pusiera el comando "rm -rf ....." creo que tal vez eso lo ocasiono porque de verdad que yo ya no le moví nada

**Comment by DrLAlbertoAngelesH** [comment]
Pero no se borro, por eso te comente que lo hicieras manualmente

**Comment by JessicaSuarezAvila** [comment]
y como la regreso? si no me sale con git branch :(

**Comment by DrLAlbertoAngelesH** [comment]
Lo más fácil es clonar tu branch y borra la carpeta actual pon en la
terminal. git clone -b NombreDeTuBranch URLparaClonar

**Comment by JessicaSuarezAvila** [comment]
![image](https://github.com/user-attachments/assets/3948a04f-6cf9-4039-9373-e7f55ee7e71a)
Ya me quedo así Profe, ya puedo subir mis archivos?
