### ISSUE TITLE
Estoy de acuerdo con mi calificación de  71, con posibilidad de entregar mi proyecto integrador hasta el 13 de Diciembre 

### ISSUE THREAD

**Issue by JessicaSuarezAvila** [DrLAlbertoAngelesH/SistemasDeManufactura-2024#337]

**Comment by DrLAlbertoAngelesH** [comment]
Hola, recuerda que solicite que hicieran un pull request solicitando aceptar su calificación, agrega tu excel con los avances que llevas, por este medio no te voy hacer valido.

Saludos,
