### ISSUE TITLE
Estoy de acuerdo con mi calificación de 74, con la posibilidad de entregar mi proyecto integrador hasta el 13 de diciembre. 

### ISSUE THREAD

**Issue by Valeriafrancobecerra** [DrLAlbertoAngelesH/SistemasDeManufactura-2024#338]

**Comment by DrLAlbertoAngelesH** [comment]
Hola, recuerda que solicite que hicieran un pull request solicitando aceptar su calificación, agrega tu excel con los avances que llevas, por este medio no te voy hacer valido.

Saludos,
