### ISSUE TITLE
HOLA

### ISSUE THREAD

**Issue by Juliahjaime** [DrLAlbertoAngelesH/SistemasDeManufactura-2024#82]
Hola profe buenas tardes, lo estamos esperando en el salón

**Comment by DrLAlbertoAngelesH** [comment]
Hola me avisaron que se suspendían las clases porque iban a fumigar

**Comment by DrLAlbertoAngelesH** [comment]
El martes continuamos no voy a subir calificaciones

**Comment by Juliahjaime** [comment]
okey profe el martes lo vemos, me comenta infante que ocupa un correo de colaboración, porque no se lo ha enviado, le puede hacer la invitación? le dejo su correo
 L21140340@queretaro.tecnm.mx

**Comment by Juliahjaime** [comment]
ya nos vamos a ir, buen puente
